DROP TABLE APT_MEMBER;
DROP TABLE RENT;
DROP TABLE MAEMAE;
DROP TABLE SCHOOL;
DROP TABLE PARK;
DROP TABLE FACILITY;
DROP TABLE LIBRARY;
DROP TABLE MY_MAEMAE;
DROP TABLE MY_RENT;

SELECT * FROM FACILITY;


/*회원테이블 만들기
 * MEM_NUM 이거 대신에 MEM_ID로 특정
 * 그리고 회원정보에 몇가지 더 추가하면 좋을 것으로 생각됨 
*/
CREATE TABLE APT_MEMBER(
	MEM_NUM NUMBER NOT NULL,
	MEM_ID VARCHAR2(10) NOT NULL, 
	MEM_PW VARCHAR2(10) NOT NULL,
	MEM_NAME VARCHAR2(10) NOT NULL,
CONSTRAINT APT_MEMBER_MEM_ID_PK PRIMARY KEY(MEM_ID)
);

/*회원코드 시퀀스 생성*/
CREATE SEQUENCE MEMBER_NUM START WITH 1 INCREMENT BY 1;
SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'MEMBER_NUM';
INSERT INTO APT_MEMBER VALUES(MEMBER_NUM.NEXTVAL,'smhrd4','12345','테스트');
SELECT * FROM APT_MEMBER;

/*전월세테이블 만들기*/
CREATE TABLE RENT(
	RENT_NUM NUMBER NOT NULL,
	DONG VARCHAR2(50) NOT NULL,
	BUILD_YEAR NUMBER NOT NULL,
	DEPOSIT VARCHAR2(10) NOT NULL,
	LOYER VARCHAR2(10),
	APT_NAME VARCHAR2(100) NOT NULL,
	YEAR NUMBER NOT NULL,
	MONTH NUMBER NOT NULL,
	DAY NUMBER NOT NULL,
	APT_SIZE NUMBER NOT NULL,
	FLOOR NUMBER NOT NULL,
constraint RENT_RENT_NUM_PK PRIMARY KEY(RENT_NUM)
);

/*전월세 시퀀스 생성*/
CREATE SEQUENCE RENT_NUM START WITH 1 INCREMENT BY 1;
SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'RENT_NUM';
INSERT INTO RENT VALUES(RENT_NUM.NEXTVAL, '4', 3,'4','5','6',7,8,9,10,11);
SELECT * FROM RENT;

/*매매테이블 만들기*/
CREATE TABLE MAEMAE(
	MAEMAE_NUM NUMBER NOT NULL,
	DONG VARCHAR2(50) NOT NULL,
	PRICE VARCHAR2(20) NOT NULL,
	BUILD_YEAR NUMBER NOT NULL,
	APT_NAME VARCHAR2(100) NOT NULL,
	YEAR NUMBER NOT NULL,
	MONTH NUMBER NOT NULL,
	DAY NUMBER NOT NULL,
	APT_SIZE NUMBER NOT NULL,
	FLOOR NUMBER NOT NULL,
	CRIME VARCHAR2(100),
	CHARGE NUMBER,
	STARBUCKS NUMBER ,
	SUBWAY VARCHAR2(10),
	MOVIE VARCHAR2(50),
constraint MAEMAE_MAEMAE_NUM_PK PRIMARY KEY(MAEMAE_NUM)
);

/*매매 시퀀스 생성*/
CREATE SEQUENCE MAEMAE_NUM START WITH 1 INCREMENT BY 1;
SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'MAEMAE_NUM';
INSERT INTO MAEMAE VALUES(MAEMAE_NUM.NEXTVAL, '4', '3',4,'5',6,7,8,9,10,11,12,13,'14','15');
SELECT * FROM MAEMAE;

/*학교테이블 만들기*/
CREATE TABLE SCHOOL(
	DONG VARCHAR2(20) NOT NULL,
	SCHOOL_NAME VARCHAR2(50) NOT NULL,
	SCHOOL_ADDR VARCHAR2(200) NOT NULL
);

/*공원테이블 만들기*/
CREATE TABLE PARK(
	DONG VARCHAR2(20) NOT NULL,
	PARK_DIV VARCHAR2(20) NOT NULL,
	PARK_SIZE VARCHAR2(10) NOT NULL
);

/*내부시설테이블 만들기*/
CREATE TABLE FACILITY(
	DONG VARCHAR2(20) NOT NULL,
	APT_NAME VARCHAR2(50) NOT NULL,
	FACILITY VARCHAR2(500) NOT NULL
);

/*도서관테이블 만들기*/
CREATE TABLE LIBRARY(
	DONG VARCHAR2(20) NOT NULL,
	LIB_NAME VARCHAR2(100) NOT NULL,
	CLOSE VARCHAR2(500) NOT NULL
);

/*법정동별 도서관 불러오기*/
SELECT DONG, LISTAGG(LIB_NAME, ', ') WITHIN GROUP (ORDER BY LIB_NAME) LIB_NAME
FROM LIBRARY 
GROUP BY DONG

/*도서관수 숫자로 보여주기 */
SELECT DONG, COUNT(*)  FROM LIBRARY GROUP BY DONG

/*매매&학교테이블 조인
 * sql 활용시 MAE.? = SCH.?; 표기하여 활용하고 '?'는 
 * get.String을 쓰겠지만 들어가는 내용은 실질 동일 이하 조인조건 동일
 * 그리고 맞춤필터는 그와 관련된 내용이 앞으로 오게 수정 이하 조인조건 동일
 * */
SELECT SCH.SCHOOL_NAME, SCH.SCHOOL_ADDR, MAE.DONG, MAE.APT_NAME, 
MAE.PRICE, MAE.BUILD_YEAR,MAE.YEAR, MAE.MONTH, MAE.DAY, MAE.APT_SIZE, MAE.FLOOR	   
FROM MAEMAE MAE, SCHOOL SCH
WHERE MAE.DONG=SCH.DONG;

/*매매&공원테이블 조인*/
SELECT PK.PARK_DIV, PK.PARK_SIZE, MAE.DONG, MAE.APT_NAME, 
	   MAE.PRICE, MAE.BUILD_YEAR, MAE.YEAR, MAE.MONTH, MAE.DAY, MAE.APT_SIZE, MAE.FLOOR	   
FROM MAEMAE MAE, PARK PK
WHERE MAE.DONG=PK.DONG;

/*매매&시설테이블 조인*/
SELECT FAC.FACILITY, MAE.DONG, MAE.APT_NAME, MAE.PRICE, MAE.BUILD_YEAR,
	   MAE.YEAR, MAE.MONTH, MAE.DAY, MAE.APT_SIZE, MAE.FLOOR	   
FROM MAEMAE MAE, FACILITY FAC
WHERE MAE.APT_NAME=FAC.APT_NAME;

/*매매&도서관테이블 조인
 *LIB.CLOSE의 경우 LIB.이 빠져 있어 여기만 수정하였습니다 
 * */
SELECT LIB.LIB_NAME, LIB.CLOSE, MAE.DONG, MAE.APT_NAME, MAE.PRICE, MAE.BUILD_YEAR,
	   MAE.YEAR, MAE.MONTH, MAE.DAY, MAE.APT_SIZE, MAE.FLOOR	   
FROM MAEMAE MAE, LIBRARY LIB
WHERE MAE.DONG=LIB.DONG


SELECT DONG, LISTAGG(LIB_NAME, ', ') WITHIN GROUP (ORDER BY LIB_NAME) LIB_NAME
FROM LIBRARY 
GROUP BY DONG

/*매매 즐겨찾기 테이블*/
CREATE TABLE MY_MAEMAE(
	MY_MAEMAE_NUM NUMBER NOT NULL,
	MAEMAE_MEM_ID VARCHAR2(10) NOT NULL,
constraint MY_MAEMAE_MY_MAEMAE_NUM_FK1 foreign key(MY_MAEMAE_NUM)
references MAEMAE(MAEMAE_NUM),
constraint MY_MAEMAE_MAEMAE_MEM_ID_FK2 foreign key(MAEMAE_MEM_ID)
references APT_MEMBER(MEM_ID)
);

/*매매 즐겨찾기 기능 확인*/
INSERT INTO MY_MAEMAE VALUES(3,'smhrd3');
SELECT * FROM MY_MAEMAE

SELECT MAEMAE_NUM,DONG,PRICE,BUILD_YEAR,APT_NAME,YEAR,
	   MONTH,DAY,APT_SIZE,FLOOR
FROM   MAEMAE
WHERE  MAEMAE_NUM IN (SELECT MY_MAEMAE_NUM
					 FROM MY_MAEMAE 
					 WHERE MAEMAE_MEM_ID IN 'smhrd2');
		

/*전월세 즐겨찾기 테이블*/
CREATE TABLE MY_RENT(
	MY_RENT_NUM NUMBER NOT NULL,
	RENT_MEM_ID VARCHAR2(10) NOT NULL,
constraint MY_RENT_MY_RENT_NUM_FK1 foreign key(MY_RENT_NUM)
references RENT(RENT_NUM),
constraint MY_RENT_RENT_MEM_ID_FK2 foreign key(RENT_MEM_ID)
references APT_MEMBER(MEM_ID)
);

/*전월세 즐겨찾기 기능 확인*/
INSERT INTO MY_RENT VALUES(2,'smhrd4');
SELECT * FROM MY_MAEMAE

SELECT RENT_NUM,DONG,BUILD_YEAR,DEPOSIT,LOYER,APT_NAME,
	   YEAR,MONTH,DAY,APT_SIZE,FLOOR
FROM   RENT
WHERE  RENT_NUM IN (SELECT MY_RENT_NUM
					 FROM MY_RENT 
					 WHERE RENT_MEM_ID IN 'smhrd4');
