DROP TABLE APT_MEMBER;
DROP TABLE RENT;
DROP TABLE MAEMAE;
DROP TABLE SCHOOL;
DROP TABLE PARK;
DROP TABLE FACILITY;
DROP TABLE LIBRARY;

SELECT * FROM FACILITY;

/*회원테이블 만들기*/
CREATE TABLE APT_MEMBER(
	MEM_NUM NUMBER NOT NULL,
	MEM_ID VARCHAR2(10) NOT NULL, 
	MEM_PW VARCHAR2(10) NOT NULL,
	MEM_NAME VARCHAR2(10) NOT NULL,
	CONSTRAINT APT_MEMBER_PK PRIMARY KEY(MEM_NUM)
);

/*회원코드 시퀀스 생성*/
CREATE SEQUENCE MEMBER_NUM START WITH 1 INCREMENT BY 1;
SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'MEMBER_NUM';
INSERT INTO APT_MEMBER VALUES(MEMBER_NUM.NEXTVAL, 'smhrd','12345','테스트');
SELECT * FROM APT_MEMBER;

/*전월세테이블 만들기*/
CREATE TABLE RENT(
	RENT_NUM NUMBER NOT NULL,
	DONG VARCHAR2(50) NOT NULL,
	BUILD_YEAR NUMBER NOT NULL,
	DEPOSIT VARCHAR2(10) NOT NULL,
	LOYER VARCHAR2(10),
	APT_NAME VARCHAR2(100) NOT NULL,
	YEAR NUMBER NOT NULL,
	MONTH NUMBER NOT NULL,
	DAY NUMBER NOT NULL,
	APT_SIZE NUMBER NOT NULL,
	FLOOR NUMBER NOT NULL
);

/*매매테이블 만들기*/
CREATE TABLE MAEMAE(
	MAEMAE_NUM NUMBER NOT NULL,
	DONG VARCHAR2(50) NOT NULL,
	PRICE VARCHAR2(20) NOT NULL,
	BUILD_YEAR NUMBER NOT NULL,
	APT_NAME VARCHAR2(100) NOT NULL,
	YEAR NUMBER NOT NULL,
	MONTH NUMBER NOT NULL,
	DAY NUMBER NOT NULL,
	APT_SIZE NUMBER NOT NULL,
	FLOOR NUMBER NOT NULL,
	CRIME VARCHAR2(100),
	CHARGE NUMBER,
	STARBUCKS NUMBER ,
	SUBWAY VARCHAR2(10),
	MOVIE VARCHAR2(50)
);

/*학교테이블 만들기*/
CREATE TABLE SCHOOL(
	DONG VARCHAR2(20) NOT NULL,
	SCHOOL_NAME VARCHAR2(50) NOT NULL,
	SCHOOL_ADDR VARCHAR2(200) NOT NULL
);

/*공원테이블 만들기*/
CREATE TABLE PARK(
	DONG VARCHAR2(20) NOT NULL,
	PARK_DIV VARCHAR2(20) NOT NULL,
	PARK_SIZE VARCHAR2(10) NOT NULL
);

/*내부시설테이블 만들기*/
CREATE TABLE FACILITY(
	DONG VARCHAR2(20) NOT NULL,
	APT_NAME VARCHAR2(50) NOT NULL,
	FACILITY VARCHAR2(500) NOT NULL
);

/*도서관테이블 만들기*/
CREATE TABLE LIBRARY(
	DONG VARCHAR2(20) NOT NULL,
	LIB_NAME VARCHAR2(100) NOT NULL,
	CLOSE VARCHAR2(500) NOT NULL
);

